In [2]:
import pandas as pd
import numpy as np
import re
import json
from funtions import *

In [4]:
#Se lee el fichero csv
df = pd.read_csv("../../master.csv", encoding='latin-1')

In [5]:
print(df.shape)

(27820, 12)

In [6]:
df.columns

Index(['ï»¿country', 'year', 'sex', 'age', 'suicides_no', 'population',
       'suicides/100k pop', 'country-year', 'HDI for year',
       ' gdp_for_year ($) ', 'gdp_per_capita ($)', 'generation'],
      dtype='object')

In [7]:
df.rename(columns={'ï»¿country':'Country','HDI for year':'HDI_for_year',' gdp_for_year ($) ':'gdp_for_year','gdp_per_capita ($)':'gdp_per_capita'},inplace=True)

In [8]:
df.columns

Index(['Country', 'year', 'sex', 'age', 'suicides_no', 'population',
       'suicides/100k pop', 'country-year', 'HDI_for_year', 'gdp_for_year',
       'gdp_per_capita', 'generation'],
      dtype='object')

In [9]:
df

,Country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI_for_year,gdp_for_year,gdp_per_capita,generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
...,...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

In [10]:
df= df.drop_duplicates()
#Vemos que únicamente hay nulos en a columna de HDI
df.isnull().sum()

Country                  0
year                     0
sex                      0
age                      0
suicides_no              0
population               0
suicides/100k pop        0
country-year             0
HDI_for_year         19456
gdp_for_year             0
gdp_per_capita           0
generation               0
dtype: int64

In [11]:
#list(df["country-year"].value_counts().items())

In [12]:

df= df[['Country', 'year', 'sex', 'age', 'suicides_no', 'population','suicides/100k pop', 'gdp_for_year','gdp_per_capita', 'generation']]

In [13]:
df["Country"].value_counts()

Austria                   382
Netherlands               382
Iceland                   382
Mauritius                 382
Colombia                  372
                         ...
Bosnia and Herzegovina     24
Macau                      12
Cabo Verde                 12
Dominica                   12
Mongolia                   10
Name: Country, Length: 101, dtype: int64

In [14]:
print("Min :",min(df["year"]) )
print("Max :",max(df["year"]) )

Min : 1985
Max : 2016

In [15]:
df["sex"].value_counts()

female    13910
male      13910
Name: sex, dtype: int64

In [16]:
df["generation"].value_counts()

Generation X       6408
Silent             6364
Millenials         5844
Boomers            4990
G.I. Generation    2744
Generation Z       1470
Name: generation, dtype: int64

In [17]:
df["age"].value_counts()

75+ years      4642
15-24 years    4642
25-34 years    4642
55-74 years    4642
35-54 years    4642
5-14 years     4610
Name: age, dtype: int64

In [18]:
#by_year = df.sort_values('gdp_per_capita',ascending = False)
#by_year

In [19]:
df["gdp_per_capita"]= df["gdp_per_capita"]*0.92
dfgY = dfToEur(df)
df['gdp_for_year'] = dfgY

La api a la que llamo puede cambiar entre muchos tipos de llamada.Para simplificar cambiare a las monedas principales

In [20]:
df["gdp_per_capitaEUR"] = change(df["gdp_per_capita"],"EUR")
df["gdp_per_capitaUSD"] = change(df["gdp_per_capita"],"USD")
df["gdp_per_capitaGBP"] = change(df["gdp_per_capita"],"GBP")
df["gdp_per_capitaJPY"] = change(df["gdp_per_capita"],"JPY")
df["gdp_per_capitaBTC"] = change(df["gdp_per_capita"],"BTC")
df["gdp_per_capitaCHF"] = change(df["gdp_per_capita"],"CHF")
df["gdp_for_yearEUR"] = change(df["gdp_for_year"],"EUR")
df["gdp_for_yearUSD"] = change(df["gdp_for_year"],"USD")
df["gdp_for_yearGBP"] = change(df["gdp_for_year"],"GBP")
df["gdp_for_yearJPY"] = change(df["gdp_for_year"],"JPY")
df["gdp_for_yearBTC"] = change(df["gdp_for_year"],"BTC")
df["gdp_for_yearCHF"] = change(df["gdp_for_year"],"CHF")

APIKEY FOUND!!
<Response [200]>
APIKEY FOUND!!
<Response [200]>
APIKEY FOUND!!
<Response [200]>
APIKEY FOUND!!
<Response [200]>
APIKEY FOUND!!
<Response [200]>
APIKEY FOUND!!
<Response [200]>
APIKEY FOUND!!
<Response [200]>
APIKEY FOUND!!
<Response [200]>
APIKEY FOUND!!
<Response [200]>
APIKEY FOUND!!
<Response [200]>
APIKEY FOUND!!
<Response [200]>
APIKEY FOUND!!
<Response [200]>

In [21]:
df.columns

Index(['Country', 'year', 'sex', 'age', 'suicides_no', 'population',
       'suicides/100k pop', 'gdp_for_year', 'gdp_per_capita', 'generation',
       'gdp_per_capitaEUR', 'gdp_per_capitaUSD', 'gdp_per_capitaGBP',
       'gdp_per_capitaJPY', 'gdp_per_capitaBTC', 'gdp_per_capitaCHF',
       'gdp_for_yearEUR', 'gdp_for_yearUSD', 'gdp_for_yearGBP',
       'gdp_for_yearJPY', 'gdp_for_yearBTC', 'gdp_for_yearCHF'],
      dtype='object')

In [22]:
df_analysis= df[['Country', 'year', 'sex', 'age', 'suicides_no', 'population',
       'suicides/100k pop', 'generation',
       'gdp_per_capitaEUR', 'gdp_per_capitaUSD', 'gdp_per_capitaGBP',
       'gdp_per_capitaJPY', 'gdp_per_capitaBTC', 'gdp_per_capitaCHF',
       'gdp_for_yearEUR', 'gdp_for_yearUSD', 'gdp_for_yearGBP',
       'gdp_for_yearJPY', 'gdp_for_yearBTC', 'gdp_for_yearCHF']]

In [23]:
df_analysis

,Country,year,sex,age,suicides_no,population,suicides/100k pop,generation,gdp_per_capitaEUR,gdp_per_capitaUSD,gdp_per_capitaGBP,gdp_per_capitaJPY,gdp_per_capitaBTC,gdp_per_capitaCHF,gdp_for_yearEUR,gdp_for_yearUSD,gdp_for_yearGBP,gdp_for_yearJPY,gdp_for_yearBTC,gdp_for_yearCHF
0,Albania,1987,male,15-24 years,21,312900,6.71,Generation X,732.32,799.070968,638.936018,86102.247915,0.116439,772.622499,1.984095e+09,2.164945e+09,1.731087e+09,2.332792e+11,3.154711e+05,2.093288e+09
1,Albania,1987,male,35-54 years,16,308000,5.19,Silent,732.32,799.070968,638.936018,86102.247915,0.116439,772.622499,1.984095e+09,2.164945e+09,1.731087e+09,2.332792e+11,3.154711e+05,2.093288e+09
2,Albania,1987,female,15-24 years,14,289700,4.83,Generation X,732.32,799.070968,638.936018,86102.247915,0.116439,772.622499,1.984095e+09,2.164945e+09,1.731087e+09,2.332792e+11,3.154711e+05,2.093288e+09
3,Albania,1987,male,75+ years,1,21800,4.59,G.I. Generation,732.32,799.070968,638.936018,86102.247915,0.116439,772.622499,1.984095e+09,2.164945e+09,1.731087e+09,2.332792e+11,3.154711e+05,2.093288e+09
4,Albania,1987,male,25-34 years,9,274300,3.28,Boomers,732.32,799.070968,638.936018,86102.247915,0.116439,772.622499,1.984095e+09,2.164945e+09,1.731087e+09,2.332792e+11,3.154711e+05,2.093288e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Generation X,2124.28,2317.908122,1853.396063,249761.420146,0.337761,2241.187626,5.802171e+10,6.331039e+10,5.062290e+10,6.821881e+12,9.225452e+06,6.121488e+10
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Silent,2124.28,2317.908122,1853.396063,249761.420146,0.337761,2241.187626,5.802171e+10,6.331039e+10,5.062290e+10,6.821881e+12,9.225452e+06,6.121488e+10
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Generation Z,2124.28,2317.908122,1853.396063,249761.420146,0.337761,2241.187626,5.802171e+10,6.331039e+10,5.062290e+10,6.821881e+12,9.225452e+06,6.121488e+10
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Generation Z,2124.28,2317.908122,1853.396063,249761.420146,0.337761,2241.187626,5.802171e+10,6.331039e+10,5.062290e+10,6.821881e+12,9.225452e+06,6.121488e+10
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Boomers,2124.28,2317.908122,1853.396063,249761.420146,0.337761,2241.187626,5.802171e+10,6.331039e+10,5.062290e+10,6.821881e+12,9.225452e+06,6.121488e+10

In [25]:

# GUARDAR EL CSV LIMPIO
df_analysis.to_csv("../OUTPUT/analysis.csv")